### ISSUE TITLE
Remove `export ROBOT_AME` to make it easier

### ISSUE THREAD

**Issue by rbo** [cloud-native-robotz-hackathon/infrastructure#130]
<img width="863" alt="Image" src="https://github.com/user-attachments/assets/0b66fcf3-a214-424b-a784-9847b2041604" />

**Comment by rbo** [comment]
That's not so easy possible. Because we doing a mapping from user `team-X` to the robot name with:
```
[source,bash,role=execute]
----
include::partial$export-{user}.adoc[]

curl -X POST http://hub-controller-live.red-hat-service-interconnect-data-center.svc.cluster.local:8080/robot/forward/2 -d user_key=${ROBOT_NAME}
----
```

**Comment by rbo** [comment]
Antora and Ascidoc extentsion looks complicated.

Let's propagate the robot name via ansible via `agnosticd_user_info`

```yaml
- name: Save user information
  when: ocp4_workload_authentication_enable_user_info_data | bool
  block:
  - name: Save user information for user access
    agnosticd_user_info:
      user: "{{ ocp4_workload_authentication_htpasswd_user_base }}{{ n + 1 }}"
      data:
        user: "{{ ocp4_workload_authentication_htpasswd_user_base }}{{ n + 1 }}"
        password: "{{ _ocp4_workload_authentication_htpasswd_user_passwords[ n ] }}"
        console_url: "{{ _ocp4_workload_authentication_console_route }}"
        openshift_console_url: "{{ _ocp4_workload_authentication_console_route }}"
        openshift_cluster_ingress_domain: "{{ _ocp4_workload_authentication_cluster_ingress_domain }}"
        login_command: >-
          oc login --insecure-skip-tls-verify=false
          -u {{ ocp4_workload_authentication_htpasswd_user_base }}{{ n + 1 }}
          -p {{ _ocp4_workload_authentication_htpasswd_user_passwords[ n ] }}
          {{ _ocp4_workload_authentication_api_server }}
    loop: "{{ range(0, ocp4_workload_authentication_htpasswd_user_count | int) | list }}"
    loop_control:
      loop_var: n
```
