### ISSUE TITLE
Evaluation if we can get rid of edge-gateway

### ISSUE THREAD

**Issue by rbo** [cloud-native-robotz-hackathon/infrastructure#134]
Meanwhile skupper should be available for ARM. What if 
* we run skupper on the robots 
* HubController on Data Center

Something like that:

![Image](https://github.com/user-attachments/assets/b56dcece-ac32-4dc7-9fab-1b35801f9fc5)

## Pro

➕ We can allow participants to use argocd to deploy applications on the robots.
➕ Extrem easy local development, because robot in local wifi/wireet network and connect the robot straigt to data center.
➕ Easier for participants to understand the setup, less black magic
➕ Easier to enable others to re-use the hackathon
➕ Less HW needed

## Cons

➖ No Edge / MicroShift Opp anymore...
➖ HubController might have to be adapted to the setup

## Ideas

- [ ] If we provide an playbook at the robots to connect to data center, we don't need an ansible env. on your local laptop.

### To check

- [ ] Robot Reboot save?

**Comment by rbo** [comment]
➕ We can allow participants to use argocd to deploy applications on the robots.

**Comment by rbo** [comment]
```
root@robocop:~# oc new-project skupper-at-robot
root@robocop:~# curl -L -O https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/helm/3.15.4/helm-linux-arm64
root@robocop:~# mv helm-linux-arm64 /usr/local/bin/helm
root@robocop:~# chmod +x /usr/local/bin/helm
root@robocop:~# helm install skupper oci://quay.io/skupper/helm/skupper --version 2.0.0-rc1
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/lib/microshift/resources/kubeadmin/kubeconfig
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /var/lib/microshift/resources/kubeadmin/kubeconfig
Pulled: quay.io/skupper/helm/skupper:2.0.0-rc1
Digest: sha256:b47134f0112088c24d8b81ea91de23a661f29cc228b8b40a8419f0c246dc3e5b
NAME: skupper
LAST DEPLOYED: Sun Feb 23 20:21:24 2025
NAMESPACE: skupper-at-robot
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
===========================================================
  Skupper chart is now installed in the cluster.
  Skupper controller was deployed in the namespace "skupper-at-robot".

===========================================================
root@robocop:~# curl -L -O https://github.com/skupperproject/skupper/releases/download/2.0.0-rc1/skupper-cli-2.0.0-rc1-linux-arm64.tgz
root@robocop:~# tar xzvf skupper-cli-2.0.0-rc1-linux-arm64.tgz
root@robocop:~# mv skupper /usr/local/bin/
root@robocop:~# skupper site generate $(hostname)
apiVersion: skupper.io/v2alpha1
kind: Site
metadata:
  name: robocop.lan

root@robocop:~#

root@robocop:~# oc apply -f - <<EOF
> apiVersion: skupper.io/v2alpha1
kind: Site
metadata:
  name: robocop.lan
> EOF
site.skupper.io/robocop.lan created
root@robocop:~#

^Croot@robocop:~# oc get pods
NAME                                  READY   STATUS    RESTARTS   AGE
skupper-controller-64557bf699-j45vj   1/1     Running   0          5m50s
skupper-router-689f5fbf45-pjt9d       2/2     Running   0          2m26s
root@robocop:~#


```

Skupper is running at the robots. Next steps:

- [ ] Connect to DataCenter
- [ ] Deploy hubcontroller at the DC, check connection robot
- [ ] Configure ArgoCD to connect to k8s api through scupper tunnel

**Comment by rbo** [comment]
Skuper 2.x is total different to skupper 1.8x

Let's uninstall and install 1.8 at the robot:
```
root@robocop:~# oc delete site robocop.lan
site.skupper.io "robocop.lan" deleted
root@robocop:~# oc get site
No resources found in skupper-at-robot namespace.
root@robocop:~# helm list
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/lib/microshift/resources/kubeadmin/kubeconfig
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /var/lib/microshift/resources/kubeadmin/kubeconfig
NAME    NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
skupper skupper-at-robot        1               2025-02-23 20:21:24.901251664 +0000 UTC deployed        skupper-2.0.0-rc1       2.0.0-rc1
root@robocop:~# helm uninstall skupper
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/lib/microshift/resources/kubeadmin/kubeconfig
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /var/lib/microshift/resources/kubeadmin/kubeconfig
release "skupper" uninstalled
root@robocop:~# oc gvet pods^C
root@robocop:~# oc get pods
No resources found in skupper-at-robot namespace.
root@robocop:~#
```

**Comment by rbo** [comment]
```
root@robocop:~# curl -L -O https://github.com/skupperproject/skupper/releases/download/1.8.3/skupper-cli-1.8.3-linux-arm64.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 19.8M  100 19.8M    0     0  6499k      0  0:00:03  0:00:03 --:--:-- 9853k
root@robocop:~# tar xzvf skupper-cli-1.8.3-linux-arm64.tgz
skupper
root@robocop:~# mv skupper /usr/local/bin/skupper
skuiproot@robocop:~# sk^C
root@robocop:~# type skupper
skupper is hashed (/usr/local/bin/skupper)
root@robocop:~# skupper version
client version                 1.8.3
transport version              not-found
controller version             not-found
config-sync version            not-found
flow-collector version         not-found
root@robocop:~#
root@robocop:~# skupper init
Waiting for status...
Skupper status is not loaded yet.
Skupper is now installed in namespace 'skupper-at-robot'.  Use 'skupper status' to get more information.
root@robocop:~# skupper status
Status pending...
root@robocop:~# oc get pods
NAME                                         READY   STATUS    RESTARTS   AGE
skupper-router-867d476476-r2rmn              1/2     Running   0          70s
skupper-service-controller-54896f888-tdzqg   0/1     Running   0          68s
root@robocop:~#

```

Expose an external services at the robot:

```
apiVersion: v1
kind: Service
metadata:
  name: robocop
  namespace: skupper-at-robot
spec:
  ports:
    - name: api
      protocol: TCP
      port: 6443
      targetPort: 6443
    - name: edge-controller
      protocol: TCP
      port: 5000
      targetPort: 5000

apiVersion: v1
kind: Endpoints
metadata:
  name: robocop
  namespace: skupper-at-robot
subsets:
- addresses:
  - ip: 192.168.66.115
  ports:
  - name: api
    port: 6443
    protocol: TCP
  - name: edge-controller
    port: 5000
    protocol: TCP

root@robocop:~# skupper expose service robocop  --address robocop
service robocop exposed as robocop
root@robocop:~# oc delete namespace skupper-at-robot^C
root@robocop:~# oc get svc
NAME                   TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                        AGE
robocop                ClusterIP   10.43.61.38    <none>        6443/TCP,5000/TCP              15m
skupper-router         ClusterIP   10.43.246.17   <none>        55671/TCP,45671/TCP,8081/TCP   25m
skupper-router-local   ClusterIP   10.43.68.59    <none>        5671/TCP                       25m
root@robocop:~# curl http://10.43.61.38/
curl: (7) Failed to connect to 10.43.61.38 port 80 after 5 ms: Network is unreachable
root@robocop:~# curl http://10.43.61.38:5000
Hackathon Robot readyroot@robocop:~#
```

At the data center:

```
oc get svc
NAME                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                        AGE
robocop                ClusterIP   172.30.189.59    <none>        6443/TCP,5000/TCP              11m


bash-5.1 ~ $ curl http://172.30.189.59:5000/
curl: (52) Empty reply from server
bash-5.1 ~ $ 

```

=> Let's try to run skupper direkt in Podman and not via microshift.
