### ISSUE TITLE
Expose robot ingress via Widlcard routes and skupper tunnel

### ISSUE THREAD

**Issue by rbo** [cloud-native-robotz-hackathon/infrastructure#160]

**Comment by rbo** [comment]
Added ingress to skupper tunnel & reverse proxy: efca5c55748ec22b7da86252e3917556365c1b47

**Comment by rbo** [comment]
## DataCenter

 => Done via ansible skupper-tunnel.yaml

```yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gort-https
  namespace: robot
spec:
  host: wildcard-https.gort.apps.cluster-f9c9p.f9c9p.sandbox663.opentlc.com
  to:
    name: gort
    weight: 100
    kind: Service
  port:
    targetPort: port443
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: Subdomain
  alternateBackends: []
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gort-http
  namespace: robot
spec:
  host: wildcard-http.gort.apps.cluster-f9c9p.f9c9p.sandbox663.opentlc.com
  path: /
  to:
    name: gort
    weight: 100
    kind: Service
  port:
    targetPort: port80
  wildcardPolicy: Subdomain
  alternateBackends: []
```

## Robot ghort for example
 
```yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: starterapp-python
  name: starterapp-python-ingress
  namespace: robot-app
spec:
  host: startapp-python.gort.apps.cluster-f9c9p.f9c9p.sandbox663.opentlc.com
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: starterapp-python
    weight: 100
  wildcardPolicy: None
```
