### ISSUE TITLE
robot.lan doesn't resolve on robots

### ISSUE THREAD

**Issue by nexus-Six** [cloud-native-robotz-hackathon/infrastructure#177]
Before it it was possible to resolve robot.lan from Microshift to access the robot api (e.g  Camera). Currently it doesn't resolve anymore.

Workaround is to add <robotname>.lan in the deployment.yaml of the robot GitOps repositories.

**Comment by rbo** [comment]
Coredns pods forwarding the DNS reqeust to the slate and not to local resolver

```shell
(.venv-ansible-navigator) root@marvin:~/infrastructure/automation# oc get pods -n openshift-dns
NAME                  READY   STATUS    RESTARTS   AGE
dns-default-slk28     2/2     Running   0          6m6s
node-resolver-j2hh4   1/1     Running   2          6d23h
(.venv-ansible-navigator) root@marvin:~/infrastructure/automation# oc rsh -n openshift-dns dns-default-slk28
Defaulted container "dns" out of: dns, kube-rbac-proxy
sh-4.4# cat /etc/resolv.conf
search lan
nameserver 192.168.8.1
sh-4.4# cat /etc/coredns/
..2025_05_23_08_35_07.416082889/ ..data/                          Corefile
sh-4.4# cat /etc/coredns/Corefile
.:5353 {
    bufsize 512
    errors
    health {
        lameduck 20s
    }
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
    }
    prometheus 127.0.0.1:9153
    forward . /etc/resolv.conf {
        policy sequential
    }
    cache 900 {
        denial 9984 30
    }
    reload
}
```

**Comment by rbo** [comment]
We can work with an k8s service:

```
apiVersion: v1
kind: Namespace
metadata:
  name: local
spec: {}
---
apiVersion: v1
kind: Service
metadata:
  name: robot
  namespace: local
spec:
  externalName: marvin
  sessionAffinity: None
  type: ExternalName
```

Or we use the reverse proxy of the skupper tunnel...

**Comment by rbo** [comment]
### Solution 1

We deploy:

```
apiVersion: v1
kind: Namespace
metadata:
  name: edge-controller
spec: {}
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: edge-controller
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: api-1
  namespace: edge-controller
  labels:
    kubernetes.io/service-name: api
addressType: IPv4
ports:
  - name: http # should match with the name of the service port defined above
    appProtocol: http
    protocol: TCP
    port: 5000
endpoints:
  - addresses:
      - "192.168.8.109" 
```

```
curl http://api.edge-controller.svc.cluster.local:5000
```

### Via NODE env variable

```
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
```

```
oc rsh simple-http-server-77d8d97b8f-b999w
sh-5.1$ echo $NODE_NAME
192.168.201.17
sh-5.1$
```
