### ISSUE TITLE
How build skupper tunnel from the robot?

### ISSUE THREAD

**Issue by rbo** [cloud-native-robotz-hackathon/infrastructure#180]
For single robot demo it would be greate to have instructions how to establish the skupper tunnel from the robot it self.

**Comment by rbo** [comment]
Let's work with Marvin (192.168.8.104)


### Prep the robot 

```shell
% ssh -i ~/.ssh/robot-hackathon -l root 192.168.8.104
root@marvin:~# apt-get install python3-venv libonig-dev
root@marvin:~# python3 -m venv /root/.venv-ansible-navigator
root@marvin:~# source /root/.venv-ansible-navigator/bin/activate
(.venv-ansible-navigator) root@marvin:~# pip install ansible-navigator
(.venv-ansible-navigator) root@marvin:~# git clone git@github.com:cloud-native-robotz-hackathon/infrastructure.git
(.venv-ansible-navigator) root@marvin:~# cd infrastructure/automation/
(.venv-ansible-navigator) root@marvin:~/infrastructure/automation# export KUBECONFIG=kubeconfig-data-center
(.venv-ansible-navigator) root@marvin:~/infrastructure/automation# oc login -u admin https://api....
(.venv-ansible-navigator) root@marvin:~/infrastructure/automation# ansible-navigator run ./skupper-tunnel.yaml --list-hosts
# Added private key
(.venv-ansible-navigator) root@marvin:~/infrastructure/automation# vim ~/.ssh/robot-hackathon
```

### Update inventory.yaml

```yaml
---
all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/robot-hackathon

datacenter:
  hosts:
    🏢-datacenter:
      ansible_connection: local

edge-gateway:
  hosts:
    🏭-edge-gateway:
      ansible_connection: local

robots:
  hosts:
    marvin:
      ansible_host: 192.168.8.104
      team: team-3
```

### Skupper tunnel
```shell
(.venv-ansible-navigator) root@marvin:~/infrastructure/automation# ansible-navigator run skupper-tunnel.yaml
```

![Image](https://github.com/user-attachments/assets/c96118b5-ba82-49f8-9e2a-03ceaaef6e56)

### Update argo

```shell
(.venv-ansible-navigator) root@marvin:~/infrastructure/automation# ansible-navigator run update-robot-to-team.yaml
```
