### ISSUE TITLE
Try pipeline as code & gitea

### ISSUE THREAD

**Issue by rbo** [cloud-native-robotz-hackathon/infrastructure#28]

**Comment by rbo** [comment]
PaC Works with webhook:

https://gitea.apps.cluster-2q7fv.2q7fv.sandbox2813.opentlc.com/team-1/starter-app-python/settings/hooks

![image](https://github.com/cloud-native-robotz-hackathon/infrastructure/assets/36604/7e3a5748-cdeb-4f82-b347-daa54d8ff634)

And a token: https://gitea.apps.cluster-2q7fv.2q7fv.sandbox2813.opentlc.com/user/settings/applications

![image](https://github.com/cloud-native-robotz-hackathon/infrastructure/assets/36604/2345cf16-23e3-4966-8477-fe17e91e810f)

**Comment by rbo** [comment]
At the OpenShift Cluster
```yaml
apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  creationTimestamp: '2024-06-27T09:05:18Z'
  generation: 4
  name: git-starter-app-python
  namespace: team-1-dev
spec:
  git_provider:
    secret:
      key: provider.token
      name: git-starter-app-python-token-8gxxt
    url: 'https://gitea.apps.cluster-2q7fv.2q7fv.sandbox2813.opentlc.com/'
    webhook_secret:
      key: webhook.secret
      name: git-starter-app-python-token-8gxxt
  url: 'https://gitea.apps.cluster-2q7fv.2q7fv.sandbox2813.opentlc.com/team-1/starter-app-python'
```
