### ISSUE TITLE
Update OpenShift AI deployment

### ISSUE THREAD

**Issue by rbo** [cloud-native-robotz-hackathon/infrastructure#29]
Red Hat OpenShift AI need service mesh for an propper installation.

**Comment by rbo** [comment]
We disabled the component at OpenShift AI:
```
    modelmeshserving:
      managementState: Removed
```

**Comment by rbo** [comment]
We should disable:
```
spec:
  components:
    kserve:
      managementState: Removed
      serving:
        ingressGateway:
          certificate:
            type: SelfSigned
        managementState: Managed
        name: knative-serving
    modelmeshserving:
      managementState: Removed
```
