### ISSUE TITLE
Workspace won't start

### ISSUE THREAD

**Issue by rbo** [cloud-native-robotz-hackathon/infrastructure#44]
```
Error provisioning rbac: roles.rbac.authorization.k8s.io "devworkspace-use-container-build" is forbidden: user "system:serviceaccount:openshift-operators:devworkspace-controller-serviceaccount" (groups=["system:serviceaccounts" "system:serviceaccounts:openshift-operators" "system:authenticated"]) is attempting to grant RBAC permissions not currently held: {APIGroups:["security.openshift.io"], Resources:["securitycontextconstraints"], ResourceNames:["container-build"], Verbs:["use"]}
```
![image](https://github.com/cloud-native-robotz-hackathon/infrastructure/assets/36604/88993f5f-164e-43a8-a0d8-e764a05a5e58)

**Comment by rbo** [comment]
Work-a-round:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:scc:container-build
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - container-build
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:scc:container-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:container-build
subjects:
- kind: ServiceAccount
  name: devworkspace-controller-serviceaccount
  namespace: openshift-operators
```
