### ISSUE TITLE
Data Science Projects page - InvalidCharacterError

### ISSUE THREAD

**Issue by rbo** [cloud-native-robotz-hackathon/infrastructure#46]
Data Science Projects page start loads and during fetching information about the Data Science Pipeline / Pipeline Server it fails with:

![image](https://github.com/cloud-native-robotz-hackathon/infrastructure/assets/36604/9c536f31-a248-4fa8-9e7f-6441ebbbb9f5)

### Component trace:
```
at https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/411.bundle.js:1:113331
    at m (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:1126160)
    at $ (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/17.bundle.js:1:16458)
    at C (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:981257)
    at z (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:984233)
    at f (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/660.bundle.js:1:6336)
    at ni (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/17.bundle.js:1:158210)
    at C (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:981257)
    at z (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:984233)
    at Suspense
    at Ht (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:1474257)
    at div
    at s (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:318061)
    at div
    at div
    at s (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:317297)
    at c (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:317514)
    at div
    at c (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:315762)
    at Ht (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:285720)
    at Ut (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:284385)
    at Gn (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:1497651)
    at u (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:1131301)
    at n (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:1450921)
    at main
    at div
    at s (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:318061)
    at div
    at div
    at s (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:317297)
    at c (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:317514)
    at div
    at c (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:315762)
    at div
    at div
    at P (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:1445483)
    at f (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:1122388)
    at Xn (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:1498061)
    at l (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:1120709)
    at ht (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:203192)
    at Ur (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:155445)
    at Qn (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:1500296)
    at Z (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:983647)
    at f (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:974538)
    at S (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:971970)
    at S (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:971970)
    at n (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:1450921)
```

### Stack trace
```
Error: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at v (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:1128107)
    at https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/411.bundle.js:1:109988
    at ol (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:931340)
    at xc (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:951470)
    at cc (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:943771)
    at Uo (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:884733)
    at https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:950272
    at Sc (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:950277)
    at ic (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:942774)
    at S (https://rhods-dashboard-redhat-ods-applications.apps.cluster-t5fkt.t5fkt.sandbox539.opentlc.com/app.bundle.js:2:996855)
```

**Comment by rbo** [comment]
If I'm deleting the datasciencepipelinesapplications, the page loads.
```
oc get datasciencepipelinesapplications  -A
NAMESPACE   NAME                   AGE
team-1-ai   pipelines-definition   16h
team-2-ai   pipelines-definition   16h
team-3-ai   pipelines-definition   16h
```

**Comment by rbo** [comment]
Deleting the  pipelines-definition and recreate does not solve the problem.

```yaml
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  name: pipelines-definition
  namespace: team-1-ai
spec:
  apiServer:
    applyTektonCustomResource: true
    archiveLogs: false
    autoUpdatePipelineDefaultVersion: true
    collectMetrics: true
    dbConfigConMaxLifetimeSec: 120
    deploy: true
    enableOauth: true
    enableSamplePipeline: false
    injectDefaultScript: true
    stripEOF: true
    terminateStatus: Cancelled
    trackArtifacts: true
  database:
    disableHealthCheck: false
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: 10Gi
      username: mlpipeline
  mlmd:
    deploy: false
  objectStorage:
    disableHealthCheck: false
    externalStorage:
      bucket: dsp-bucket-ab256b91-7dd7-4d5b-8e73-29d1f566e126
      host: s3.openshift-storage.svc
      port: ""
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: dsp-bucket
      scheme: http
  persistenceAgent:
    deploy: true
    numWorkers: 2
  scheduledWorkflow:
    cronScheduleTimezone: UTC
    deploy: true
```
