### ISSUE TITLE
robot-app pipeline failed 

### ISSUE THREAD

**Issue by rbo** [cloud-native-robotz-hackathon/infrastructure#58]
```
The node was low on resource: ephemeral-storage. Threshold quantity: 16015370671, available: 12622432Ki. Container step-build-and-push was using 8447016Ki, request is 0, has larger consumption of ephemeral-storage.
```

![image](https://github.com/user-attachments/assets/0dfa6852-0a1d-480e-945c-ba9634869dc6)

**Comment by rbo** [comment]
New cluster, and try to build https://github.com/cloud-native-robotz-hackathon/starter-app-python/commit/f67feb32ae33908bc18d0849cb8bcd24122c7911 failed on x64 nodes as well.

FYI, size of the arm image:
```
default-route-openshift-image-registry.apps.cluster-bdw98.bdw98.sandbox1004.opentlc.com/team-1-dev/starter-app-python  test-arm64  092eac33ae58  28 minutes ago  1.57 GB
```

**Comment by rbo** [comment]
Added 
```
      computeResources:
        requests:
          ephemeral-storage: "1Gi"
        limits:
          ephemeral-storage: "10Gi"
```

Pod Evicted as well.

```
The node was low on resource: ephemeral-storage. Threshold quantity: 16015370671, available: 14083620Ki.

```

How to fetch ephemeral-storage from node:
```
kubectl get --raw "/api/v1/nodes/<node>/proxy/stats/summary" | jq '.pods[] | select(.podRef.name=="pod-name") '
```
