### ISSUE TITLE
Prep solution to upload trained model into s3 bucket for model server

### ISSUE THREAD

**Issue by rbo** [cloud-native-robotz-hackathon/infrastructure#83]
Download the trained model from quay [0] and upload to local workbench-bucket.

[0] https://quay.io/repository/cloud-native-robotz-hackathon/model-container?tab=tags&tag=latest

**Comment by rbo** [comment]
Upload via:
```
apiVersion: v1
kind: Pod
metadata:
  generateName: model-restore-pod-
spec:
  restartPolicy: Never
  containers:
  - name: upload
    image: quay.io/cloud-native-robotz-hackathon/model-container:trained-uploader-1.25.83
    envFrom:
    - secretRef:
        name: workbench-bucket-ai-connection
    command:
    - /bin/sh
    - -c
    - |

      set -x

      aws configure list
      aws s3 --no-verify-ssl cp \
         /model/robot_onnx/1/model.onnx \
         s3://$AWS_S3_BUCKET/models/model-latest.onnx \
         --endpoint-url $AWS_S3_ENDPOINT


```

trained-uploader-1.25.83 container build with:


```
FROM quay.io/cloud-native-robotz-hackathon/ubi-awscli:1.25.83

ADD model /model

USER 0
RUN chmod -R g+rwx /model
```


```
./model
./model/robot_onnx
./model/robot_onnx/1
./model/robot_onnx/1/model.onnx
./Containerfile
```
